baseURL: https://mpilosov.com
languageCode: en-us
title: "Mathematical Michael"
theme: dimension
Params:
  author: Michael Pilosov
  url: https://github.com/mathematicalmichael
  logo: icons/mult.svg
  sharing: true
  custom_font_color: '#fff'
  headings_color: '#fff'
  border_color: '#e83e8c'
  border_logo: '#fff'
  border_menus: '#fff'
  body_bg: '#1b1f22'
  article_bg: '#1b1f22'
  bg_grad_from: 'rgba(19, 21, 25, 0.5)'
  bg_grad_to: 'rgba(19, 21, 25, 0.5)'
  bg_delay: '0s'
  bg_fade_in: '1.5s'
  header_delay: '0s'
  header_fade_in: '1s'
  header_transition: '1.5s'
  article_transition: '0.5s' # these two dont seem to work
  text_transition: '0.5s'
  version: 1